import crypto from 'node:crypto';

const defaultDate = () => new Date().toISOString().slice(0, 10);

const xmlEscape = (value) =>
  String(value ?? '')
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;');

const compactXml = (value) => value.replace(/>\s+</g, '><').trim();

export const HMRC_ENDPOINTS = {
  test: 'https://test-transaction-engine.tax.service.gov.uk/submission',
  live: 'https://transaction-engine.tax.service.gov.uk/submission'
};

const deriveIrmark = (bodyWithoutIrmark) => {
  const compact = compactXml(bodyWithoutIrmark);
  return crypto.createHash('sha1').update(compact, 'utf8').digest('base64');
};

const numeric = (value) => Number(value || 0).toFixed(2);

export function buildSaReturnBody(payload = {}, estimate = {}) {
  const personal = payload.personal ?? {};
  const incomes = payload.incomes ?? {};
  const reliefs = payload.reliefs ?? {};
  const declaration = payload.declaration ?? {};

  const taxYear = payload.taxYear || '2025-26';
  const periodEnd = payload.periodEnd || '2026-04-05';
  const estimatedTaxDue = estimate?.breakdown?.balanceDue ?? 0;

  const draftWithoutIrmark = `
<IRenvelope xmlns="http://www.govtalk.gov.uk/taxation/SA/SA100/2026-1" FullSubmission="yes">
  <IRheader>
    <Keys>
      <Key Type="UTR">${xmlEscape(personal.utr)}</Key>
    </Keys>
    <PeriodEnd>${xmlEscape(periodEnd)}</PeriodEnd>
    <DefaultCurrency>GBP</DefaultCurrency>
    <Manifesto>Self Assessment return draft generated by MVP software</Manifesto>
    <IRmark Type="generic"></IRmark>
  </IRheader>
  <SA100>
    <TaxYear>${xmlEscape(taxYear)}</TaxYear>
    <YourPersonalDetails>
      <FirstName>${xmlEscape(personal.firstName)}</FirstName>
      <LastName>${xmlEscape(personal.lastName)}</LastName>
      <DateOfBirth>${xmlEscape(personal.dateOfBirth)}</DateOfBirth>
      <NationalInsuranceNumber>${xmlEscape(personal.nino)}</NationalInsuranceNumber>
      <Email>${xmlEscape(personal.email)}</Email>
    </YourPersonalDetails>
    <Income>
      <Employment>${numeric(incomes.employment)}</Employment>
      <SelfEmployment>${numeric(incomes.selfEmployment)}</SelfEmployment>
      <Property>${numeric(incomes.property)}</Property>
      <SavingsInterest>${numeric(incomes.interest)}</SavingsInterest>
      <Dividends>${numeric(incomes.dividends)}</Dividends>
      <Pension>${numeric(incomes.pension)}</Pension>
      <Other>${numeric(incomes.other)}</Other>
    </Income>
    <Reliefs>
      <PensionContributions>${numeric(reliefs.pensionContributions)}</PensionContributions>
      <GiftAid>${numeric(reliefs.giftAid)}</GiftAid>
      <Losses>${numeric(reliefs.losses)}</Losses>
    </Reliefs>
    <Computation>
      <EstimatedTaxDue>${numeric(estimatedTaxDue)}</EstimatedTaxDue>
    </Computation>
    <Declaration>
      <Accepted>${declaration.accepted ? 'true' : 'false'}</Accepted>
      <AcceptedAt>${xmlEscape(declaration.acceptedAt || new Date().toISOString())}</AcceptedAt>
    </Declaration>
  </SA100>
</IRenvelope>`.trim();

  const irmark = deriveIrmark(draftWithoutIrmark);
  return draftWithoutIrmark.replace(
    '<IRmark Type="generic"></IRmark>',
    `<IRmark Type="generic">${irmark}</IRmark>`
  );
}

export function buildGovTalkEnvelope({
  bodyXml,
  credentials = {},
  className = 'HMRC-SA-SA100',
  functionName = 'submit',
  qualifier = 'request',
  testMode = true,
  correlationId = ''
}) {
  const channel = {
    uri: credentials.channelUri || 'mvp.local.tax-software',
    product: credentials.product || 'TaxSoftwareMVP',
    version: credentials.productVersion || '0.1.0'
  };

  return `
<?xml version="1.0" encoding="UTF-8"?>
<GovTalkMessage xmlns="http://www.govtalk.gov.uk/CM/envelope">
  <EnvelopeVersion>2.0</EnvelopeVersion>
  <Header>
    <MessageDetails>
      <Class>${xmlEscape(className)}</Class>
      <Qualifier>${xmlEscape(qualifier)}</Qualifier>
      <Function>${xmlEscape(functionName)}</Function>
      <Transformation>XML</Transformation>
      <GatewayTest>${testMode ? '1' : '0'}</GatewayTest>
      ${
        correlationId
          ? `<CorrelationID>${xmlEscape(correlationId)}</CorrelationID>`
          : ''
      }
    </MessageDetails>
    <SenderDetails>
      <IDAuthentication>
        <SenderID>${xmlEscape(credentials.senderId)}</SenderID>
        <Authentication>
          <Method>clear</Method>
          <Role>principal</Role>
          <Value>${xmlEscape(credentials.password)}</Value>
        </Authentication>
      </IDAuthentication>
    </SenderDetails>
  </Header>
  <GovTalkDetails>
    <Keys>
      <Key Type="UTR">${xmlEscape(credentials.utr)}</Key>
    </Keys>
    <TargetDetails>
      <Organisation>HMRC</Organisation>
    </TargetDetails>
    <ChannelRouting>
      <Channel>
        <URI>${xmlEscape(channel.uri)}</URI>
        <Product>${xmlEscape(channel.product)}</Product>
        <Version>${xmlEscape(channel.version)}</Version>
      </Channel>
    </ChannelRouting>
  </GovTalkDetails>
  <Body>
${bodyXml}
  </Body>
</GovTalkMessage>`.trim();
}

export function buildGovTalkSubmissionXml({ payload, estimate, credentials, testMode = true }) {
  const body = buildSaReturnBody(payload, estimate);
  return buildGovTalkEnvelope({
    bodyXml: body,
    credentials,
    className: 'HMRC-SA-SA100',
    functionName: 'submit',
    qualifier: 'request',
    testMode
  });
}

export function buildGovTalkPollXml({ credentials, correlationId, className = 'HMRC-SA-SA100', testMode = true }) {
  const body = `
<IRpoll>
  <Class>${xmlEscape(className)}</Class>
  <CorrelationID>${xmlEscape(correlationId)}</CorrelationID>
  <PollAt>${xmlEscape(defaultDate())}</PollAt>
</IRpoll>`.trim();

  return buildGovTalkEnvelope({
    bodyXml: body,
    credentials,
    className,
    functionName: 'query',
    qualifier: 'request',
    testMode,
    correlationId
  });
}

export function buildGovTalkDeleteXml({ credentials, correlationId, className = 'HMRC-SA-SA100', testMode = true }) {
  const body = `
<IRdelete>
  <Class>${xmlEscape(className)}</Class>
  <CorrelationID>${xmlEscape(correlationId)}</CorrelationID>
</IRdelete>`.trim();

  return buildGovTalkEnvelope({
    bodyXml: body,
    credentials,
    className,
    functionName: 'delete',
    qualifier: 'request',
    testMode,
    correlationId
  });
}

const extract = (text, tag) => {
  const match = text.match(new RegExp(`<${tag}>([\\s\\S]*?)</${tag}>`, 'i'));
  return match ? match[1].trim() : null;
};

export function summariseHmrcResponse(xmlText) {
  const status = extract(xmlText, 'Status') || extract(xmlText, 'Qualifier');
  const correlationId = extract(xmlText, 'CorrelationID');
  const responseEndPoint = extract(xmlText, 'ResponseEndPoint');

  return {
    status,
    correlationId,
    responseEndPoint
  };
}

export function detectHmrcError(xmlText) {
  const errorNumber = extract(xmlText, 'Number');
  const errorText = extract(xmlText, 'Text');

  if (!errorNumber && !errorText) {
    return null;
  }

  return {
    code: errorNumber,
    message: errorText
  };
}
